### PR TITLE
CRITICAL Fart fix (also adds duct tape and inflatable walls)

### LINKED ISSUE #132: Admin heal/revive probably doesn't regenerate teeth
Best place to put might be here: https://github.com/HippieStation/HippieStation13/blob/06460f9673702c9753622d75e92ef2e5efb98fa9/code/modules/surgery/organs/organ_internal.dm#L710

This is called by fully_heal and in turn revive.

Also stripping people removes their organis

### LINKED ISSUE #139: Tape
Tape and Tape-related stuff should be re-added such as:
Makeshift Armor
Tray Shields
Makeshift Muzzle

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
add: Duct tape and inflatables
fix: Fixes farts
/:cl:

Fixes #139
Fixes #132

### CODE REVIEW

**Comment by yobob591** [comment]
yes

**Comment by JohnGinnane** [comment]
What's wrong with farts

**Comment by Pyko1** [comment]
Should prolly re-add the ductapes to our lootdrop spawners as well.

**Comment by Pyko1** [comment]
I can slap the inflatable barriers on the map on my next mapping PR tho.

**Review by j-mie — APPROVED** [review]

**Pull request merged**
