### PR TITLE
Space Hotel Pool

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
add: The Space Hotel has an actual pool now, instead of just a blue floor.
/:cl:

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by cacogen** [comment]
i mean i don't disapprove of the changes but the space hotel barely gets used, and when it does the pool receives zero use. plus it's far too big.

the entire thing should be scaled down to better fit the population it usually receives.

**Comment by j-mie** [comment]
Needs a picture

**Comment by j-mie** [comment]
retest this please

**Comment by j-mie** [comment]
@HonkBot retest this please

**Comment by j-mie** [comment]
retest this please

**Comment by ghost** [comment]
Can one of the admins verify this patch?

**Comment by j-mie** [comment]
build this

**Pull request merged**
