### PR TITLE
heavily nerfs ebows

### PR DESCRIPTION
**Pull request by ghost**
:cl: ErikHanson
del: You can no longer perma-stun someone by just shooting him with ebow bolts, oh and did i tell you that you could just keep clicking because they reloaded faster than you can click? Yeah good job TG
/:cl:

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Oldcode: https://github.com/HippieStationCode/HippieStation13/blob/56a3fdddeb58b6e0dedb20514f4cc43bee628c58/code/modules/projectiles/projectile/energy.dm#L131

**Comment by KittyKathy** [comment]
He ded tag when, it looks pretty much the same now as it was in old code the only difference is that it was stronger in old code because it could not be blocked. Also this is 12 tc I would expect something good for that amount of tc.

**Comment by JohnGinnane** [comment]
So you could kill someone on oldcode with a few shots and permastun?

**Comment by Pyko1** [comment]
Looks pretty damn weak for 12 TC

**Comment by KayeArray** [comment]
meh

**Comment by cacogen** [comment]
gonna order one of these next time i roll traitor thanks dade

**Pull request closed without merging**
