### PR TITLE
Tts hook

### PR DESCRIPTION
**Pull request by TDcoolguy300**
Too tired to do a proper CL, will do it tomorrow

### CODE REVIEW

**Comment by j-mie** [comment]
Doesn't work, The clients have to download the file from the server :(

https://github.com/d3athrow/vgstation13/blob/5bd1779503cc28ee85b7b1f33580d721f47b7d27/goon/browserassets/js/browserOutput.js#L436-L442

**Comment by ghost** [comment]
Correct, this way of implementing it is bad, just merge goonchat and i'll eventually get to adding TTS

**Comment by KayeArray** [comment]
awwww ye boi


but yeah wait for the goon chat shit so we can make some proper good TTS shit yo

**Comment by ghost** [comment]
I'd support this feature if it auto turned on during an april fools event.

**Comment by tortellinitony** [comment]
Closed by request

**Pull request closed without merging**
