### PR TITLE
Revert "Updates parallax space default toggle to be disabled temporarily"

### PR DESCRIPTION
**Pull request by Iamgoofball**
Reverts HippieStation/HippieStation13#252

have you considered not speedmerging this shit

### CODE REVIEW

**Comment by ghost** [comment]
@Iamgoofball why should we revert this? Players are having issues, they can toggle it on if they want to

**Comment by Iamgoofball** [comment]
@Chnkr Tell players to upgrade their drivers and software, don't accomodate lazy fuckwits.

**Comment by tortellinitony** [comment]
yes we do, this is hippie @Iamgoofball

**Comment by Iamgoofball** [comment]
@tortellinitony that's retarded

**Comment by KayeArray** [comment]
parallax is broke as fuck nerd

**Comment by Iamgoofball** [comment]
Update BYOND and update your drivers, nerd.

**Comment by j-mie** [comment]
@Iamgoofball If you want to break the game for your players go ahead, but we're happy with having this not set as default and having functional shit by default, rather then a potentially wonky feature which sometimes works depending on what version of BYOND you have, what drivers you have, what OS you're running and if you have the DirectX SDK installed...

**Comment by Iamgoofball** [comment]
Holy shit, it's not hard to just update BYOND. The directX thing is piss easy. Stop being a retard.

**Comment by KayeArray** [comment]
no u

**Comment by j-mie** [comment]
@Iamgoofball alternatively we could not have features enabled by default which break shit for players. This is our code base, we'll do what ever the fuck we want - don't be an asshole @Iamgoofball

**Pull request closed without merging**
