### PR TITLE
Botany Changes

### LINKED ISSUE #295: Bottles do not visually show their fill level
In-Game report from vexingraven:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-20

>Revision (Should be above if you're viewing this from ingame!)
I can't find it, but the current version as of 2/20/2017

>General description of the issue
Bottles do not visually deplete and empty like they used to. I believe this started after one of the fixes that went in today that was supposed to fix the lag, the same one that made playes start the round invisible went it first went through.

>What you expected to happen
When filling and emptying a bottle its sprite should visually show this fill level. When emptied it should turn into a completely empty bottle. Similar to how beakers do.

>What actually happened
When emptying a bottle, its sprite does not update at all.

>Steps to reproduce if possible
Fill a bottle, empty a bottle. Easiest as a chemist.

### PR DESCRIPTION
**Pull request by KittyKathy**
:cl: Kitty Kathy and McBawbaggings
add: Botany now starts off with unstable mutagen and other things they need in the vending machines
add: Botany also gets back biogenerator designs from pre rebase with some new options
add: Adds back botany tray freezing just use a multitool on it.
tweak: The biogenerator works more like the autolathe now
tweak: Robust Harvest now doubles yield like pre rebase
tweak: Most if not all bottles should now be the color the chemicals inside are
tweak: Botany seed machine now starts with 10 more strange seeds but it requires a coin for each
/:cl:
Fixes #295 though the tank sprite does not have sprites anymore for determining their water level.
Ports https://github.com/HippieStationCode/HippieStation13/pull/2778
I guess you could say this is refactoring a bit.
Everything a botanist could need is now in their vending machine no need to go grab tools at round start and grab a chem dispenser or ask the chemist to maybe help you out. There are enough supplies for 3 botanist maybe more if they share and minimize their usage until they get melons or grass for the biogenerator. 
Tray freezing works differently than pre rebase you can still add chemicals and do other stuff to the tray while the plant is frozen the only thing is you can't harvest while frozen.
Probably forget to list some changes but it's probably minor and just quality of life improvements to botany.
When you add stuff to vending machines that can be restocked you have to edit vending_items.dm to reflect those changes. This did not happen for vapes and some other stuff when 2 vapes were supposed to be available without it being hacked only 1 would be there. I fixed it by correcting the file and editing the vending machines so they had a total item count divisible by 3 as a restock replenish 1/3 of the items.
Added 10 more strange seeds to the seed machine as a premium item that needs a coin for each seed because they are pretty cool but are only randomized when they are created as in when they call new() planting and growing more and turning them into seeds will give you the same thing you planted not something random again.
*Updated for new changes

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by KayeArray** [comment]
sounds good

**Comment by PopNotes** [comment]
good shit good shit that's some good shit right there

**Comment by ghost** [comment]
wew, someone liked my botany idea
+1

**Comment by KayeArray** [comment]
yes you are an hero

**Comment by PopNotes** [comment]
We will Make Plants Great Again

**Comment by JohnGinnane** [comment]
@KittyKathy your conflict is quite interesting. I think to fix this:

1. Switch to your master branch and update that
2. Copy the now updated vending.dm somewhere
3. Switch back to botantmutants and put the copied vending.dm where it should be
4. Change vending.dm to have the items you wanted originally

**Comment by KittyKathy** [comment]
~Don't merge for now,~ I'm working on improving the biogenerator menu as it is just one big list.
*edited well ready to be checked now should be better than one big list like a vending machine

**Pull request merged**
