### PR TITLE
Moves the vault back to the old location

### PR DESCRIPTION
**Pull request by ghost**
The current vault is in a rather out-of-sight location, this PR intends to fix that by moving the vault to a more suitable location

:cl: ErikHanson
tweak: The vault has been moved!
/:cl:

### CODE REVIEW

**Comment by Sarcalogo** [comment]
Nah.

**Comment by j-mie** [comment]
@Sarcalogo real good constructive criticism, if "Nah" is all you've got to say, give it a thumbs down using the reactions instead please instead of shitting up our comments with "Nah"

**Comment by cacogen** [comment]
i think the way it's mapped looks kind of clunky (though maybe that's just because i'm not used to it) and it doesn't really seem like an issue.

the vault is pretty near the bridge in a relatively high traffic hallway, and nothing of any real value is stored in there anyway.

**Comment by j-mie** [comment]
@cacogen apart from all the stations money...

**Comment by Pyko1** [comment]
I see no mapping issues really, besides that the gravity SMES isn't wired to grid, but it hasn't really ever been on TG.

But I don't really like the layout tho, i prefer the cubic space separated vault more, especially since it takes at least some effort for chemists to break in other than splash and ignite.

**Comment by JohnGinnane** [comment]
Not sure I like how easy it would be to get into vault like that

**Comment by j-mie** [comment]
build this

**Comment by Nokington** [comment]
just move the gravity gen back to engineering? this just looks awful

**Pull request closed without merging**
