### PR TITLE
Bootleg announcers - Fake a central message

### PR DESCRIPTION
**Pull request by ghost**
:cl: coiax
add: Central Command have reported that various communication encryption keys have been stolen. The use of these keys could HYPOTHETICALLY allow faking of secure Central Command messages, or disruption of intelligence dispatches. Central Command reassure all Nanotrasen stations that the chances of this happening are very slim.
add: Adds bootleg announcer to uplink, costs 5 TC, fake a Central Command message! The messages will require admin approval, but the device is refundable if there's no one online, or the admins aren't feeling like it.
add: Adds intel disruption device to uplink, costs 10 TC, fake an "all
clear message" to the station, and watch as the extended suicides pile up.
/:cl:

### CODE REVIEW

**Comment by Spacedong** [comment]
if you want an admin announcement just ask lmao -1

**Comment by cacogen** [comment]
for what purpose

**Comment by Pyko1** [comment]
Somehow I feel this is a bad idea.

If nothing else it would entirely discredit any and all centcom messages.

**Comment by PKPenguin321** [comment]
We rejected this at /tg/ because it would basically make you unable to run events with centcomm messages as an admin

**Comment by j-mie** [comment]
build this

**Comment by ghost** [comment]
I'm not feeling it either, I'd rather tc trade instead.

**Pull request closed without merging**
