### PR TITLE
Adds three crates with cargo transporters in science's experimentor room.

### PR DESCRIPTION
**Pull request by jediluke1999**
I've added three crates, each with one cargo transporter, into the EXPERIMENTOR room in science. I figured that, since mining usually takes the ORM down to lavaland and that they don't like to come to upgrade it anyways, that RND might appreciate sending the materials over to them. Also, observant medbay inhabitants might appreciate upgrading their own machines. Deus vult.

~I also don't know how to add tags to my own pull-request or issues. If that's a headmin thing, then cool. Otherwise, I apologize. I want to have pumped up kicks like all the other kids.

### CODE REVIEW

**Comment by jediluke1999** [comment]
Ah, thanks a ton. Also, how do I go about making mapping changes properly, for the future?

**Comment by JohnGinnane** [comment]
Take a gander at https://tgstation13.org/wiki/Map_Merger

**Comment by JohnGinnane** [comment]
For the change you should change your OP to be like this:

🆑 jediluke1999
add: Added three crates with cargo...
/🆑

here you can discuss things that aren't included in the changelog

**Comment by ghost** [comment]
I'm good with this, just make the required changes as removing .yml file and adding the changelog to the OP. Mapmerge isn't essential but vastly preferred.

**Comment by jediluke1999** [comment]
Okay, thanks a ton. I'll close this pull request and make sure to start another one. Again, thanks a ton.

**Pull request closed without merging**
