### PR TITLE
Syndicate communication/services for sale

### PR DESCRIPTION
**Pull request by ghost**
:cl: coiax
add: Central Command have reported that various communication encryption
keys have been stolen. The use of these keys could HYPOTHETICALLY allow
faking of secure Central Command messages, or disruption of intelligence
dispatches. Central Command reassure all Nanotrasen stations that the
chances of this happening are very slim.
add: Adds bootleg announcer to uplink, costs 5 TC, fake a Central
Command message!
add: Adds intel disruption device to uplink, costs 10 TC, fake an "all
clear message" to the station, and watch as the extended suicides pile up.
/:cl:

port of https://github.com/tgstation/tgstation/pull/24172 with one slight change to prevent HTML injection by using `stripped_multiline_input`

### CODE REVIEW

**Comment by coiax** [comment]
the fiends

**Comment by JohnMcLaime** [comment]
5 and 10 tc is too much, people are less likely to suicide over that message because it can be antag who sent it, same with trusting centcom messages.

**Comment by j-mie** [comment]
Add the thing so admins can deny it and refund to stop abuse please.

**Comment by ghost** [comment]
@JamieH sure

**Pull request closed without merging**
