### PR TITLE
Gives catbeasts the tail and ear bodyparts instead of having them in the sprite

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
add: Cats have proper tail/ear bodyparts
/:cl:

https://gfycat.com/HardGentleBustard

### CODE REVIEW

**Comment by KittyKathy** [comment]
inb4 people confuse kitty ears headgear for catbeast and lynch them.

**Comment by tortellinitony** [comment]
humans don't have the rainbow skin though

**Comment by KittyKathy** [comment]
Can't you get that though with like colorful reagent, but you can still tell by the facial structure unless obscured with a mask. new meta wear cat ears gas mask pretend to be a cat beast kill everyone in self defense, I love it.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
The code looks good, not sure about the sprites tbh

**Comment by PopNotes** [comment]
dear god that looks terrible

**Comment by tortellinitony** [comment]
those are long standing sprites that have been there for like a year now :man_shrugging:

**Comment by Spacedong** [comment]
that looks awful but not comically awful like actually awful

**Comment by cacogen** [comment]
i mean they won't be alive for very long anyway

also i bet the tail still wags when they're dead

**Comment by PopNotes** [comment]
it still looks shitty, delet this

**Comment by Pyko1** [comment]
Naah, add this!
Just get someone to make better sprites first.

**Comment by tortellinitony** [comment]
*wag emote to wag.

**Comment by ghost** [comment]
Bad sprites, looks awful.

**Comment by ghost** [comment]
Stale PR, Awful sprites, feel free to re-open this if i did a bad

**Pull request closed without merging**
