### PR TITLE
Fixes cluwnes and vape

### LINKED ISSUE #258: Curse of the Cluwne is broken
In-Game report from zadingtons:
Revision info: Server revision dc9d53ae76738c0b6b138846b52d8417c92d1ee7 compiled on: 2017-02-18

It shows up in your hud and spells tab, but when you click it nothing happens. Also missing a proper icon for the spell button.

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
fix: Fixed cluwnes and the curse of cluwne.
fix: Fixed vape.
/:cl:

Fixes #258

### CODE REVIEW

**Comment by KittyKathy** [comment]
Looks good one question though is there a difference between using `cut_overlays()` and `overlays.Cut()`? If there is which one is better to use?

**Comment by tortellinitony** [comment]
I don't know, but it was not working before and there was a recent overlay change, so I just changed it.

**Review by ghost — DISMISSED** [review]
**_Please do not manually change the overlays_**

Use `/proc/cut_overlays()` and `/proc/add_overlay(image, priority = 0)` so that overlay changes do not cause any lag

**Review by JohnGinnane — APPROVED** [review]
Looks good, merging

**Pull request merged**
