### PR TITLE
"playerbase: shit feature" ok.

### PR DESCRIPTION
**Pull request by ghost**
¯\_(ツ)_/¯

### CODE REVIEW

**Review by j-mie — APPROVED** [review]

**Comment by KittyKathy** [comment]
Already? I did not even get to play with those change...was it ear rape or something?

**Comment by ghost** [comment]
@KittyKathy players didn't like it, so its gone now

**Comment by KittyKathy** [comment]
What did they not like about It? I played goon before It never bothered me when I played there.

**Comment by cacogen** [comment]
F

**Pull request merged**
