### PR TITLE
Iamgoofball's shitty effects and a catban fix

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
add: Spicy new effects for foam and stuff
fix: Hopefully fixed catbans
/:cl:

https://github.com/tgstation/tgstation/pull/23885

### CODE REVIEW

**Comment by KittyKathy** [comment]
Hmm shouldn't you wait until goofs stuff gets merged before you port it to save yourself doing more work?

**Comment by tortellinitony** [comment]
I fixed all the stuff people were complaining about

**Comment by KittyKathy** [comment]
Uh quick question why are you removing the crashed ship space ruins?
also you might have missed some stuff because I still see a variable named tempsfsadf.
alpha_fade is using 1s and 0s instead of TRUE and FALSE.

**Comment by tortellinitony** [comment]
the ruins cause a pirate runtime arrrg

I'll change it to true and false if you really want and I'll change that variable

**Review by j-mie — APPROVED** [review]

**Comment by j-mie** [comment]
Looks good to me, Someone else?

**Pull request merged**
