### PR TITLE
Adds actual links and info to the hub

### PR DESCRIPTION
**Pull request by tortellinitony**
A button that says 'default' and leads nowhere just will not do!

Maybe we should add a picture like CM. Anyone have a cool banner? Link it.

### CODE REVIEW

**Comment by JohnGinnane** [comment]
How come you removed the other details like number of players?

**Comment by tortellinitony** [comment]
The playercount bit is old and archaic: there is a more accurate player list on both the hub and the pager. The gamemode bit is unnecessary: it is almost always secret, and admins will use force secret mode even when they are letting the gamemode be known, just so it does not show up in the hub. The AI is always allowed. There is never respawn. Etc. This looks better and gets rid of all the clutter.

**Comment by ghost** [comment]
> Maybe we should add a picture like CM. Anyone have a cool banner? Link it.

Yes.

**Review by JohnGinnane — APPROVED** [review]
Looks good

**Comment by JohnGinnane** [comment]
I'm down, might want @JamieH opinion

**Pull request merged**
