### PR TITLE
Ports plasma weaponry, modifies ERT and DS loadout

### PR DESCRIPTION
**Pull request by KayeArray**
:cl: Banthebantz
add: Readds plasma weaponry for ERT and Deathsquad, comes as both combi revolver and rifle
add: Plasma weaponry is highly damaging but lacks range and has a high energy draw
tweak: Tweaked ERT and DS loadouts accordingly, now normal ERT commanders get a combi revolver, High alert get a rifle, DS all get combi revolvers in place of the mateba and DS officer gets a plasma rifle in place of the pulse

/:cl:

[]: Port of the plasma weapons I added pre rebase, mainly a fun pulse weapon sidegrade and a nasty surprise for those murderboners worthy of a red alert ERT or deathsquad call.

Currently using pulse rifle inhand sprite for the plasma rifle because I can't get it to work with my one.

### CODE REVIEW

**Comment by KayeArray** [comment]
hmmm why'd it do that?

**Review by ghost — APPROVED** [review]

**Review by ghost — DISMISSED** [review]
jenkins says no

**Comment by KayeArray** [comment]
yes can you explain why? it compiles fine for me

**Comment by ghost** [comment]
You forgot the `.dme`

**Comment by KayeArray** [comment]
wait you need that?

**Comment by ghost** [comment]
Yes

**Comment by KayeArray** [comment]
is ded?

**Review by tortellinitony — APPROVED** [review]
looks good and was already approved on the old codebase

**Pull request merged**
