### PR TITLE
Old vox sounds

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
soundadd: Adds old vox sounds.
fix: Nerfs vox_login.
/:cl:

### CODE REVIEW

**Comment by tortellinitony** [comment]
PSA you can toggle vox in the preferences tab under hear/silence announcements.

**Comment by ghost** [comment]
Ass Blast USA. +1

**Review by ghost — APPROVED** [review]

**Comment by cacogen** [comment]
the hl1 sounds?

**Comment by Sarcalogo** [comment]
Can you just add a toggle between the male and female voices? Some prefer the female voice.

**Comment by KayeArray** [comment]
hl1 vox best vox

**Pull request merged**
