### PR TITLE
Fixed various sprites

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
add: Added a RoboTech to robotics.
fix: Redid a number of sprites.
/:cl:

Fixed the vending machine sprites, the tank sprites, and the cheap lighter sprite.

### CODE REVIEW

**Comment by ghost** [comment]
@tortellinitony screenshots please

**Comment by tortellinitony** [comment]
https://vgy.me/u2zFSW.png

**Comment by Spacedong** [comment]
Just port these back so it doesn't conflict with the artstyle

**Comment by Spacedong** [comment]
You didn't really kill the goon sprites, you just altered their positions, they still look like shit because they use the goon artstyle which we don't fully have.

**Comment by tortellinitony** [comment]
no they don't

**Comment by Spacedong** [comment]
They completely clash with the rest of the artstyle.

**Comment by KittyKathy** [comment]
Is Spacedong the art director of this server?

**Comment by ghost** [comment]
looks weird man

**Comment by KittyKathy** [comment]
When are we getting these water tank sprites? https://github.com/tgstation/tgstation/pull/24421

**Comment by Spacedong** [comment]
just restore the old artstyle sprites please

**Comment by tortellinitony** [comment]
spacedong you're complaining about these sprites but you must be actually retarded cause these are literally the old watertank sprites

**Comment by Spacedong** [comment]
no the vending sprites dude

**Comment by Spacedong** [comment]
f i x   t h e    v e n d o r s

**Comment by tortellinitony** [comment]
I don't even think you know what you're saying when you state that they look like goon sprites

http://i.imgur.com/zBOAQAs.jpg

They are in the old artstyle, not the 3/4s one.

**Comment by Spacedong** [comment]
no they're still not, just restore the sprites I posted

**Comment by Spacedong** [comment]
you just edited the perspective, the artstyle is still from goon.

**Comment by tortellinitony** [comment]
Spacedong, you don't know what you are talking about.

**Comment by cacogen** [comment]
do we have to have the oxygen tank sprite? it looks like ass
didn't we already have that at one point after the rebase and then it got changed back?

this whole sprite debate on both servers has reminded me how subjective the entire thing is though tbh

**Comment by j-mie** [comment]
I'm going to merge this, if people still aren't happy - let's revert to our old ones.

**Review by j-mie — APPROVED** [review]

**Pull request merged**
