### PR TITLE
fucks up the cats

### PR DESCRIPTION
**Pull request by ghost**
:cl: Spacedong
add: Nanotrasen has forgone all disability checks on its Tajaran personnel. All catbeasts now spawn with crippling disabilities such as epilepsy, coughing, clumsiness, and stupidity.
/:cl:

### CODE REVIEW

**Comment by cacogen** [comment]
????

**Comment by KittyKathy** [comment]
Where is the joy of the hunt when can barely move? That's what epilepsy does right? stuns them and making them stupid makes them unable to use doors due to headbutting it is not fun man. This is like cluwne 2.0 except you can pick it round start without asking for a ban.

**Comment by cacogen** [comment]
this just screams grudgecoding

they're already valid, is that not enough?

**Comment by MethMedic** [comment]
This makes them the same as cluwnes. It's retarded fuck you

**Comment by tortellinitony** [comment]
yea we could just add cluwnebans instead

**Comment by JohnGinnane** [comment]
https://github.com/HippieStationCode/HippieStation13/blob/7cfe6d8854248e226e437b6a705245ec170db815/code/modules/mob/living/carbon/human/species_types.dm#L159

**Comment by KittyKathy** [comment]
Dongcode
https://github.com/HippieStationCode/HippieStation13/pull/2625
Where is the SALTDong tag, do people really get dunked by catbeasts enough to warrant this? because if so that's hilarious and we need to make fun of those people.

**Comment by yobob591** [comment]
just remove the epilepsy or make it only a chance that they spawn with it, other disabilities are fine

**Comment by Spacedong** [comment]
do not port cluwnes back, just port this

**Comment by ghost** [comment]
cluwnes dont even fit here, keep the cats

**Comment by tortellinitony** [comment]
Cluwnes are already here hahahahahha

**Comment by Pyko1** [comment]
Didn't we had to do some transformation sting nerfs because of this and cluwnes?

**Comment by ghost** [comment]
@Pyko1 I think that the normal transformation sting should not change races, we should add a special sting that does cluwnes/cats

**Pull request closed without merging**
