### PR TITLE
Electrocution limits have been removed, crank up that power!

### PR DESCRIPTION
**Pull request by ghost**
:cl: ErikHanson
del: Electrocution is no longer capped to 90, instead it's now capped at 500
/:cl:

### CODE REVIEW

**Comment by KayeArray** [comment]
Add the motherfucking tesla effect to APCs

**Comment by McHatters** [comment]
What exactly does this mean? Will shocks when cutting wires still damage the player?

**Comment by ghost** [comment]
@McHatters yes, the damage used to be capped at `90` but this removes the limit and allows you to be instakilled

**Comment by McHatters** [comment]
oh fuck that's gonna be nasty
I can already see the traitor engineers who decide to wire the singulo directly into the power grid, then hack every door so that it shocks people who try to open it

**Comment by KittyKathy** [comment]
Does this in anyway affect the Telsa?

**Review by TDcoolguy300 — APPROVED** [review]
I mean, it's just a number change

**Comment by ghost** [comment]
fuark yea

**Pull request merged**
