### PR TITLE
gives clown and mime maint #112

### LINKED ISSUE #112: Clowns and mimes lack maint access.
WHAT THE ACTUAL FUCK /TG/!!!!

### PR DESCRIPTION
**Pull request by cacogen**
:cl: cacogen
add: gives clown and mime maint
/:cl:

Fixes #112

### CODE REVIEW

**Comment by JohnGinnane** [comment]
Fix looks good, did you test it? Join game as clown or l'île and confirm your ID has access

**Comment by JohnGinnane** [comment]
I also edited the OP to say "Fixes #issue" so that when it's merged it should automatically close the issue

**Review by JohnGinnane — APPROVED** [review]
Code is good

**Comment by cacogen** [comment]
Yup, I did. It works fine.

**Comment by JohnGinnane** [comment]
Cool, merging so

**Pull request merged**
