### PR TITLE
Fixes color-change of smoke and foam

### LINKED ISSUE #361: foam from cleaner grenades is incorrectly layered
the foam appears on top of people

### PR DESCRIPTION
**Pull request by tortellinitony**
:cl: Tortellini Tony
fix: Fixed animation issues with foam and smoke.
/:cl:

Fixes #361

### CODE REVIEW

**Review by TDcoolguy300 — APPROVED** [review]
Suire

**Comment by j-mie** [comment]
This PR is bad, you need to use INVOKE_ASYNC and ADDTIMER

**Comment by j-mie** [comment]
addtimer example: ```addtimer(CALLBACK(src, .proc/Shed, H, FALSE), 50)```
INVOKE_ASYNC example: ```INVOKE_ASYNC(src, .proc/open_door, door)```

**Comment by ghost** [comment]
we dont even need a spawn there ???

**Pull request merged**
